### ISSUE TITLE
why not getSession to get metadata ? 

### ISSUE THREAD

**Issue by ozexpert** [nolanlawson/pouchdb-authentication#102]
Couple questions. 

1. I see no use case of having getSession() if no metadata is returned.
seems everytime when user opens the app, we need to get call getSession() to see whether user is logged in and then call getUser() to get user data? 

2. and in the document, you were saying it works with the remote database. If so, why do we need to do sync with local database? 

3. If no network, would calling getUser() gets user data from local? (I believe not.. )
if so, do I need to store in local storage after calling getUser() ? and if getSession() returns data, then call from local storage to display user infomation if OFFLINE? (just asking what's the best practice for this kind of scenario). 

Thanks!

**Comment by nolanlawson** [comment]
1. Right, `getSession()` just checks whether the user is logged in.
2. That's just an API decision for convenience. Actually `new PouchDB('http://wherever')` is a handle on a remote CouchDB anyway.
3. No, `getUser()` is all remote. You shouldn't need to store anything in local storage, because CouchDB authentication is handled automatically via cookies.

Probably it's helpful to understand that `pouchdb-authentication` is less about PouchDB and more about CouchDB. Really it's just a set of helper methods that each map to a CouchDB REST API. The fact that it's a PouchDB plugin is just for convenience. You could do it all yourself with Ajax too and it would be the same.

Hope that clears things up a bit!
