### ISSUE TITLE
doesn't work in node

### ISSUE THREAD

**Issue by slang800** [nolanlawson/pouchdb-authentication#18]
fails with `ReferenceError: XMLHttpRequest is not defined`

**Comment by nolanlawson** [comment]
Yeah, this isn't designed as a Node.js module. I'd recommend [nano](https://github.com/dscape/nano#using-cookie-authentication).

**Comment by slang800** [comment]
Actually, pouchdb itself does work with Node.js (so no need for nano), and pouchdb-authentication is a node.js module: https://www.npmjs.com/package/pouchdb-authentication (which is why I found it odd that it would be throwing errors when used in node).

But I ended up just using the built-in pouchdb auth:
```
new PouchDB("https://username:password@example.com/db-name")
```
...so no worries.

**Comment by svnlto** [comment]
I'd be curious if you'd use https://github.com/driverdan/node-XMLHttpRequest internal it would work on node..

**Comment by nolanlawson** [comment]
You probably could! :) Assuming the cookies could be set correctly.

**Comment by denis-sokolov** [comment]
But why? It seems that 636b4bc78b3 broke Node on purpose.
I test my browser apps using `jsdom` on Node and the rest of PouchDB works without any problems.
Even outside of testing, it seems nicer to share code between the client and the server instead of using separate modules. What was the reason to break it?
Also, `0.1.4` seems to work fine, I think I'll be using that for now.

**Comment by nolanlawson** [comment]
I didn't try to break Node. The reason I don't support Node for this module is that it's intended to be a simple reference implementation for CouchDB's cookie system. In Node you can just skip cookies entirely and use HTTP authentication, then serve up whatever authentication system you want, since you have control of the server.

As for `jsdom`, I have no idea, but you may want to file a bug over there.

**Comment by denis-sokolov** [comment]
@nolanlawson, I may have misled you. There is no bug with `jsdom` or anything else.

Your library does not support Node.js, and I can't use it on Node.js. I need to use it on Node.js because I test my browser code in Node.js for convenience. Everything else works, as does `pouchdb-authentication` up to `0.1.4`.
There is a second reason to use `pouchdb-authentication` on Node - when I share some code between my client and my server, and both use Couch with auth, it's easier to use exactly the same code.

Any chance you reconsider to support Node.js or shall I look for alternative routes to my problem?

**Comment by nolanlawson** [comment]
I honestly don't know what you mean by "broken in Node." If you'd like to submit a pull request, and if it doesn't add excessive additional complexity, I'd be happy to accept it. :)

**Comment by denis-sokolov** [comment]
Until 636b4bc the module supported two ways to do http requests - one for Node (`ajax.js`) and one for browser (`ajax-browser.js`). This is an example where unfortunately, a part of a codebase must be split for the two platforms. On the flip side - everything else works the same in Node and in the browser.

Will you accept a PR adding a non-browser `ajax` back in?

**Comment by nolanlawson** [comment]
I'd accept a PR using the new `pouchdb-ajax` module, which works in both Node and the browser.

**Comment by nolanlawson** [comment]
Actually scratch that; we are going with another solution for exposing `ajax`: https://github.com/pouchdb/pouchdb/pull/3730

**Comment by nolanlawson** [comment]
Should be working in Node again as of 0.3.7 because we're using PouchDB's ajax module. Lemme know if that doesn't fix it.
