### ISSUE TITLE
Unknown error when calling db.signup()

### ISSUE THREAD

**Issue by RichardLitt** [nolanlawson/pouchdb-authentication#37]
I'm trying to sign up a user, and I'm getting an exception labelled `// HTTP error, cosmic rays, etc.`. I'm not sure how to deal with this issue, and I don't know why it is called. 

The code is [here](https://github.com/RichardLitt/beagle-heroku/blob/master/auth.js#L80-L99), and I've no idea how to start diagnosing. What do you think?

**Comment by fourstar04** [comment]
hey @RichardLitt  i am working through this right now too.  I need to spend some time on my angular factory and try this couch setting out but I think that this might explain what is causing this issue for me. 

I found in the ionic forum somebody added that you need to make sure you have this couchdb setting

CouchDB-Settings required:
[couch_httpd_auth]
require_valid_user = false

Currently, I am guessing that I am having this same error as you because this is not in my couchdb and the new user cant sign up because they are not yet a valid user.

 I will try to confirm this, I just wanted to throw this out there in the mean time.  Maybe somebody has experience with this I am a total couch noob right now.

http://forum.ionicframework.com/t/using-pouchdb-plugins-inside-ionic-demo-code-requested/14788

**Comment by RichardLitt** [comment]
Hey @fourstar04 - thanks! Hmm. I'm not sure that I have the same issue; I was able to fix it in PR #38 by making sure that my `metadata` object I send as a param didn't have an embedded `metadata` object within it. That seemed to have fixed it. Try that?

**Comment by fourstar04** [comment]
oh hey thanks that makes sense.  glad you have found your solution.  i am probably all wrong here but thought that i would chime in in case i was on to something.  i think my problem might have been because i was trying to send in the ajax headers with the signup request, removing that prevented this error for me.

**Comment by nolanlawson** [comment]
Can you print out the `err.stack` to see what the error is? My hunch is that cosmic rays are not at fault.

**Comment by RichardLitt** [comment]
Cannot reproduce. Was probably due to `salt` being used twice. Will reopen if I run into it again.

**Comment by RichardLitt** [comment]
And thanks!
