### ISSUE TITLE
Offline authentication?  Is it possible

### ISSUE THREAD

**Issue by markbarton** [nolanlawson/pouchdb-authentication#52]
Hi,

Just looking at the documentation and its quite clear that the PouchDB instance for authentication must be remote and not local.  Is it at all possible for local authentication?

My scenario is consultants working offline in a hospital which need to create new orders and read existing offline data, so they will already be registered and replicated locally.  My plan was to use a Chrome packaged app but I am wondering now if I need to go the whole hog and using something like node-webkit or nwjs as its now known.

Thanks

Mark

**Comment by nolanlawson** [comment]
So this plugin is just a sugar API over CouchDB's cookie-based authentication, but since PouchDB is designed from the ground-up to be offline-first, there's no reason you couldn't use it in the kind of app you describe.

Steps:

1. Store data locally
2. When the user is online, use this plugin to call CouchDB and store the cookie. Else, retry periodically if you get an error
3. Try to sync periodically (using PouchDB's `sync()` or `replicate()`. If you get errors, it's either because A) the user is offline, or B) the user is not logged in.

BTW for what it's worth, PouchDB tends to work much better in NW.js than Chrome packages apps because Chrome packaged apps have some weird restrictions (such as not being able to call `eval()`).

**Comment by markbarton** [comment]
Thanks for that.

So it looks like local storage will not be necessarily authenticated - because there will be no way to authenticate that cookie.

Still that shouldn't be too bad - they would have had to authenticate to access the server-side instance anyway to do the initial replication - so the only security hole is a stolen laptop and in that instance the protection would be provided by a combination of the BIOS / OS with whole disk encryption.

I did see someone had some working code with Chrome packaged apps & pouchdb - the main advantage for us is the use of Chromebooks and deployment / management of the app, if we can get it working, even if we have to keep the offline version of the application as simple as possible I would like to try and use a Chome App if not NW.js will be the way forward.

**Comment by markbarton** [comment]
When I say someone - I think it was you that built http://www.chromepouch.com/  - so again thanks!!  This offline stuff is hard isn't it - for a long time I did IBM Lotus Notes development and never realised how lucky I was with the offline client.

**Comment by nolanlawson** [comment]
Nope, I did not build http://www.chromepouch.com/ but that is very neat! :) Never seen that site before.

Disk encryption is one option; there is also [crypto-pouch](https://github.com/calvinmetcalf/crypto-pouch) which can do the encryption within PouchDB.
