### ISSUE TITLE
Signup / login

### ISSUE THREAD

**Issue by czb** [nolanlawson/pouchdb-authentication#57]
Hi,

why do you require existence of PouchDB for Signup and Login? The only thing that you need is url of the server. Then you would avoid the '{skipSetup: true}'. I am in the situation where I do not know the database url before I log in. So I have to create dummy PouchDB just to login. Sounds overcomplicated to me.

**Comment by nolanlawson** [comment]
Thanks for the feedback! It was indeed an awkward design decision, but I did it because it made the implementation simpler to package it as a PouchDB plugin. You are absolutely right that the dummy PouchDB is kind of silly. I welcome any alternative module that just directly uses some XHR/fetch implementation. :)
