### ISSUE TITLE
Problem with Cloudant

### ISSUE THREAD

**Issue by sebrojas14** [nolanlawson/pouchdb-authentication#95]
I always getting the 403 error. This is my user documment in _users:

{
 "_id": "3ae2b004f63f76a1d936b0cce2e96d2c",
 "_rev": "3-77f93ee6a9e99d6769dc528c0bcb82bf",
 "value": {
  "rev": "3-77f93ee6a9e99d6769dc528c0bcb82bf"
 },
 "key": "3ae2b004f63f76a1d936b0cce2e96d2c",
 "doc": {
  "_id": "3ae2b004f63f76a1d936b0cce2e96d2c",
  "_rev": "3-77f93ee6a9e99d6769dc528c0bcb82bf",
  "name": "admin",
  "roles": [
   "_reader",
   "_writer"
  ],
  "type": "user",
  "password": "37d6c5Qe"
 }
}

I'm calling db.login('admin', '37d6c5Qe')

**Comment by nolanlawson** [comment]
I don't believe pouchdb-authentication supports Cloudant. I'm told they were working on adding support, but last I heard it's not in yet. You can contact Cloudant customer support for more help.

**Comment by sebrojas14** [comment]
Yes, I make a suppport request, I will come back here.

**Comment by Kluskey** [comment]
@sebrojas14 Any updates?

**Comment by numerized** [comment]
So, after playing a bit with cloudant Ionic2 and pouchdb-authentication I can tell you that they are 100% compatible.

The error is happening because Cloudant don't user the _user database as we expect.

When you signup a new user db.signup() with any cloudant database as remote, the user is created in the _user database but no entry is sent to the permission schema inside cloudant database.

Cloudant manage users differently by generating API keys and checking granted roles.

The catch is to add a user in the Permissions schema of the database through cloudant console where the actual user has been created and grant him some roles.

The way cloudant is actually creating users is to generate an API key for the database of your choice like explained here : 
https://docs.cloudant.com/authorization.html

At the bottom of the previous link it's mentioned that is possible to use the _user database to manage users. I'll check that in a couple of hours and report here : 

> 
You can use the _users database to manage roles in Cloudant. However, you must turn off Cloudant security for those roles first. To do this, PUT a JSON document to the _security endpoint of the database. For example, https://<username>.cloudant.com/<database>/_security.
>

You can use Node to do it for you : 
https://github.com/cloudant/nodejs-cloudant#generate-an-api-key
